// autogenerated by typings-for-css-modules-loader.
declare namespace CounterModuleScssNamespace {
  export interface ICounterModuleScss {
    counter: string;
  }
}

declare const CounterModuleScssModule: CounterModuleScssNamespace.ICounterModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CounterModuleScssNamespace.ICounterModuleScss;
};

export = CounterModuleScssModule;
